## CLUSTER OF THE NEIGHBOUHOODS OF TORONTO

This project cluster the neigbourhood of Toronto from Wikipedia data

Before we start with the main lab content, let's download all the dependencies that we will need.

In [2]:
import pandas as pd
import requests
import numpy as np

In [5]:
#!pip3 install lxml  #this doesn't work and I always get the message "lxml not found, please install it" when trying to scrape the wiki table

### DOWNLOAD THE DATA AND SAVE IT IN A PANDAS DATA FRAME

tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_postal_codes_of_Canada:_M', header=0)

headings = ['Postal Code', 'Borough', 'Neighbourhood']

for table in tables:
    current_headings = table.columns.values[:3]
    if len(current_headings) != len(headings):
        continue
    if all(current_headings == headings):
        break
        
table[headings].to_csv('Toronto_data.csv', sep=';', header=True, index=False)
        
#Note: It was imposible to me to get the table directly in the notebook. I always got an error with lxml parse. I try to install it but it was imposible to me so the previous code was run on my personal computer.
#I then saved the table on a csv and import that csv file here

In [32]:
#This is to charge the data from the csv file due to the problems in the lxml intalation on the notebook

toronto_df = pd.read_csv("test.csv",sep=';')
toronto_df

,Postal Code,Borough,Neighbourhood
0,M1A,Not assigned,Not assigned
1,M2A,Not assigned,Not assigned
2,M3A,North York,Parkwoods
3,M4A,North York,Victoria Village
4,M5A,Downtown Toronto,"Regent Park, Harbourfront"
...,...,...,...
175,M5Z,Not assigned,Not assigned
176,M6Z,Not assigned,Not assigned
177,M7Z,Not assigned,Not assigned
178,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."
179,M9Z,Not assigned,Not assigned

### Delete the 'Not Assigned' Boroughs

In [33]:
toronto_df=df = toronto_df.drop(toronto_df[toronto_df.Borough == 'Not assigned'].index)

In [34]:
toronto_df = toronto_df.reset_index(drop=True)
toronto_df

,Postal Code,Borough,Neighbourhood
0,M3A,North York,Parkwoods
1,M4A,North York,Victoria Village
2,M5A,Downtown Toronto,"Regent Park, Harbourfront"
3,M6A,North York,"Lawrence Manor, Lawrence Heights"
4,M7A,Downtown Toronto,"Queen's Park, Ontario Provincial Government"
...,...,...,...
98,M8X,Etobicoke,"The Kingsway, Montgomery Road, Old Mill North"
99,M4Y,Downtown Toronto,Church and Wellesley
100,M7Y,East Toronto,"Business reply mail Processing Centre, South C..."
101,M8Y,Etobicoke,"Old Mill South, King's Mill Park, Sunnylea, Hu..."
102,M8Z,Etobicoke,"Mimico NW, The Queensway West, South of Bloor,..."

As it can be seen the neighbourhood with the same postal code are listed on the same row separated by colons

In [35]:
notass = toronto_df[toronto_df['Neighbourhood'] == 'Not assigned'] 
notass

Empty DataFrame
Columns: [Postal Code, Borough, Neighbourhood]
Index: []

There are not 'Not assigned' neigbourhood with an assigned Borough

In [36]:
toronto_df.shape

(103, 3)

In [108]:
toronto_df.to_csv('Canada_data.csv', sep=';', header=True, index=False)