# Retrive latitude and longitude from every postal code

In [2]:
import pandas as pd

In [3]:
lonlat_data=pd.read_csv('http://cocl.us/Geospatial_data')

lonlat_data

    Postal Code   Latitude  Longitude
0           M1B  43.806686 -79.194353
1           M1C  43.784535 -79.160497
2           M1E  43.763573 -79.188711
3           M1G  43.770992 -79.216917
4           M1H  43.773136 -79.239476
..          ...        ...        ...
98          M9N  43.706876 -79.518188
99          M9P  43.696319 -79.532242
100         M9R  43.688905 -79.554724
101         M9V  43.739416 -79.588437
102         M9W  43.706748 -79.594054

[103 rows x 3 columns]

## Sort the Canada table by Postal code to merge the latitude and longitude

Open the Canada data storged

In [4]:
toronto_df = pd.read_csv("Canada_data.csv",sep=';')

Sort the table

In [5]:
toronto_df=toronto_df.sort_values(by=['Postal Code'])
toronto_df = toronto_df.reset_index(drop=True)
toronto_df

,Postal Code,Borough,Neighbourhood,Latitude,Longitude
0,M1B,Scarborough,"Malvern, Rouge",43.806686,-79.194353
1,M1C,Scarborough,"Rouge Hill, Port Union, Highland Creek",43.784535,-79.160497
2,M1E,Scarborough,"Guildwood, Morningside, West Hill",43.763573,-79.188711
3,M1G,Scarborough,Woburn,43.770992,-79.216917
4,M1H,Scarborough,Cedarbrae,43.773136,-79.239476
...,...,...,...,...,...
98,M9N,York,Weston,43.706876,-79.518188
99,M9P,Etobicoke,Westmount,43.696319,-79.532242
100,M9R,Etobicoke,"Kingsview Village, St. Phillips, Martin Grove ...",43.688905,-79.554724
101,M9V,Etobicoke,"South Steeles, Silverstone, Humbergate, Jamest...",43.739416,-79.588437
102,M9W,Etobicoke,"Northwest, West Humber - Clairville",43.706748,-79.594054

Add latitude and longitude data

In [ ]:
toronto_df['Latitude']=lonlat_data.Latitude
toronto_df['Longitude']=lonlat_data.Longitude
toronto_df

Save the data for the exploration and clustering

In [8]:
toronto_df.to_csv('Canada_lonlat.csv', sep=';', header=True, index=False)